import { CampaignRow } from '@/types'

export const mapToSupabase = (row: CampaignRow, userId: string) => ({
  id: row.id,
  data_inicio: row.startDate || null,
  data_fim: row.endDate || null,
  plataforma_canal: row.platform || '',
  nome_campanha: row.campaign || '',
  publico: row.audience || '',
  investimento: row.cost || 0,
  impressoes: row.impressions || 0,
  alcance: row.reach || 0,
  cliques_rd: row.clicksRD || 0,
  cliques_ads: row.clicksAds || 0,
  ctr: row.impressions && row.impressions > 0 ? (row.clicksAds || 0) / row.impressions : 0,
  dif_cliques: (row.clicksAds || 0) - (row.clicksRD || 0),
  leads_plan: row.leadsSalesSheet || 0,
  leads_rd: row.leadsRD || 0,
  cvl: row.clicksAds && row.clicksAds > 0 ? (row.leadsRD || 0) / row.clicksAds : 0,
  orcamentos_qtd: row.quoteQty || 0,
  valor_orcamento: row.quoteValue || 0,
  pedidos_qtd: row.orderQty || 0,
  valor_pedidos: row.orderValue || 0,
  leads_orcamento: row.quoteQty && row.quoteQty > 0 ? (row.leadsRD || 0) / row.quoteQty : 0,
  orcamento_pedido: row.orderQty && row.orderQty > 0 ? (row.quoteQty || 0) / row.orderQty : 0,
  usuario_id: userId,
})

export const mapFromSupabase = (row: any): CampaignRow => ({
  id: row.id,
  startDate: row.data_inicio || '',
  endDate: row.data_fim || '',
  platform: row.plataforma_canal || '',
  campaign: row.nome_campanha || '',
  audience: row.publico || '',
  cost: Number(row.investimento || 0),
  impressions: Number(row.impressoes || 0),
  reach: Number(row.alcance || 0),
  clicksRD: Number(row.cliques_rd || 0),
  clicksAds: Number(row.cliques_ads || 0),
  ctr: Number(row.ctr || 0),
  diffClicks: Number(row.dif_cliques || 0),
  leadsSalesSheet: Number(row.leads_plan || 0),
  leadsRD: Number(row.leads_rd || 0),
  cvl: Number(row.cvl || 0),
  quoteQty: Number(row.orcamentos_qtd || 0),
  quoteValue: Number(row.valor_orcamento || 0),
  orderQty: Number(row.pedidos_qtd || 0),
  orderValue: Number(row.valor_pedidos || 0),
  leadsPerBudget: Number(row.leads_orcamento || 0),
  budgetPerOrder: Number(row.orcamento_pedido || 0),
  version: 1,
  createdAt: row.criado_em,
})
